---
language: generic
dist: trusty
group: edge
sudo: true
before_install:
- if [[ $BUILDER = docker ]] ; then sudo stop docker ; sudo cat /etc/default/docker
  ; echo 'DOCKER_OPTS="$DOCKER_OPTS --storage-opt dm.basesize=20G"' | sudo tee -a
  /etc/default/docker ; sudo cat /etc/default/docker ; sudo start docker ; sleep 5
  ; sudo docker version ; fi
install:
- git clone --branch="master" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf 6214fcdff7fb51a89ac38757d1ab6fbd96beff1f
  ; popd
- if [[ "$(packer version 2>/dev/null)" != "Packer v0.10.1" ]] ; then make -C packer-templates
  install-packer ; fi
- "./packer-templates/bin/packer-build-install"
script:
- "./packer-templates/bin/packer-build-script ci-connie"
env:
  matrix:
  - BUILDER=googlecompute
  - BUILDER=docker
