
dist: bionic
before_install:
- sudo apt update -qq

## Install snapd
- sudo apt install snapd --yes
- export PATH=/snap/bin/:$PATH

## Install and setup ZFS
- sudo apt install zfsutils-linux --yes
- sudo mkdir -p /mnt/data

## Install and setup LXD
- sudo apt remove --purge --yes lxd lxd-client liblxc1 lxcfs
- sudo snap install lxd
- sudo snap set lxd shiftfs.enable=true

- sudo lxc storage create instances zfs volume.zfs.use_refquota=true
- sudo zfs set sync=disabled instances
- sudo zfs set atime=off instances
- sudo lxc storage create data dir source=/mnt/data
- sudo lxc network create lxdbr0 dns.mode=none ipv4.address=192.168.0.1/24 ipv4.dhcp=true ipv4.firewall=false ipv4.nat=true
- sudo lxc profile device add default eth0 nic nictype=bridged parent=lxdbr0 security.mac_filtering=true
- sudo lxc profile device add default root disk path=/ pool=instances

- sudo apt install curl unzip make --yes
- curl -sLo /tmp/packer_1.5.1_linux_amd64.zip https://releases.hashicorp.com/packer/1.5.1/packer_1.5.1_linux_amd64.zip
- sudo unzip /tmp/packer_1.5.1_linux_amd64.zip -d /usr/bin

- sudo snap install ruby --classic
- sudo snap install aws-cli --classic
- mkdir -p ~/.config/lxc
- sudo cp /etc/lxc/default.conf ~/.config/lxc/default.conf
install:
- git clone --branch=lxd-xenial "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf @ ; popd
- "./packer-templates/bin/packer-build-install"
script:
- export PACKER_TEMPLATES_BRANCH="lxd-xenial"
- export TRAVIS_COOKBOOKS_BRANCH="master"
- "pushd packer-templates && make ci-sardonyx && popd"
# addons:
#   artifacts:
#     paths:
#     - image-metadata-$(cat .packer-build-image-name).tar.bz2
#     target_paths:
#     - travis-ci/packer-templates/ci-freebsd-12/$BUILDER
# notifications:
#   email: false
# env:
#   matrix:
#   - BUILDER=googlecompute
