---
language: minimal
dist: trusty
group: edge
sudo: true
env:
  global:
  - PACKER_LOG=1
  matrix:
  - BUILDER=docker
before_install:
- if [[ "${BUILDER}" = "docker" ]] ; then sudo apt-get update -yqq ; sudo apt-get
  purge -o Dpkg::Options::="--force-confnew" -yqq docker-ce ; sudo apt-get install
  -o Dpkg::Options::="--force-confnew" -yqq docker-ce lvm2 xfsprogs ; echo 'DOCKER_OPTS="$DOCKER_OPTS
  --storage-driver devicemapper"' | sudo tee -a /etc/default/docker ; sudo service
  docker restart ; fi
install:
- git clone --branch="edmorley-packer-error-testcase" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf @ ; popd
- "./packer-templates/bin/packer-build-install"
script:
- export PACKER_TEMPLATES_BRANCH="edmorley-packer-error-testcase"
- "./packer-templates/bin/packer-build-script ci-opal"
