
language: minimal
dist: xenial

install:
- git clone --branch=lxd-templates "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf @ ; popd

env:
  global:
    - BUILDER="lxd"
    - TEMPLATE="ubuntu-16.04-minimal"
  jobs:
    - ARCH="ppc64le"; BUILDER_HOTS=$BUILDER_ppc64le
    - ARCH="arm64"; BUILDER_HOTS=$BUILDER_arm64

script:
- make $TEMPLATE
