---
language: minimal
dist: xenial
group: edge
env:
  global:
  - PACKER_TEMPLATES_BRANCH="master"
  - TRAVIS_COOKBOOKS_BRANCH="master"
  jobs:
  - BUILDER=googlecompute
  - BUILDER=docker
  #- BUILDER=openstack
  
befote_install:
 - sudo apt update
 - sudo apt upgrade

install:
- git clone --branch="${PACKER_TEMPLATES_BRANCH}" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf @ ; popd
- "./packer-templates/bin/packer-build-install"
script:
- "./packer-templates/bin/packer-build-script ci-stevonnie"
addons:
  artifacts:
    paths:
    - image-metadata-$(cat .packer-build-image-name).tar.bz2
    target_paths:
    - travis-ci/packer-templates/ci-stevonnie/$BUILDER
notifications:
  email: false
