---
language: minimal
dist: bionic
group: dev
sudo: true
before_install:
- if [[ "${BUILDER}" = "docker" ]] ; then sudo cat /etc/docker/daemon.json;
  sudo systemctl stop docker;
  sudo cp ${TRAVIS_BUILD_DIR}/daemon.json /etc/docker/daemon.json;
  sudo cat /etc/docker/daemon.json;
  sudo ps auxf | grep docker;
  sudo systemctl start docker ; fi
install:
- git clone --branch="${PACKER_TEMPLATES_BRANCH}" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf @ ; popd
- "./packer-templates/bin/packer-build-install"
script:
- "./packer-templates/bin/packer-build-script ci-ubuntu-1804-minimal"
addons:
  artifacts:
    paths:
    - image-metadata-$(cat .packer-build-image-name).tar.bz2
    target_paths:
    - travis-ci/packer-templates/ci-ubuntu-1804-minimal/$BUILDER
notifications:
  email: false
env:
  global:
  - PACKER_TEMPLATES_BRANCH="master"
  - TRAVIS_COOKBOOKS_BRANCH="master"
  matrix:
  - BUILDER=docker
  - BUILDER=googlecompute