---
language: generic
dist: trusty
group: edge
sudo: true
install:
- git clone --branch="meat-lil-worker-docker" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf cbc3700740d4 ; popd
- "./packer-templates/bin/packer-build-install"
script:
- export PACKER_TEMPLATES_BRANCH="meat-lil-worker-docker"
- "./packer-templates/bin/packer-build-script internal-bastion"
env:
  matrix:
  - BUILDER=amazon-ebs
  - BUILDER=googlecompute
