---
language: generic
dist: trusty
group: edge
sudo: true
install:
- git clone --depth=50 "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git fetch origin +refs/pull/276/merge && git checkout
  -qf FETCH_HEAD ; popd
- "./packer-templates/bin/packer-build-install"
script:
- export PACKER_TEMPLATES_BRANCH="+refs/pull/276/merge"
- "./packer-templates/bin/packer-build-script internal-bastion"
env:
  matrix:
  - BUILDER=amazon-ebs
  - BUILDER=googlecompute
