---
language: generic
dist: trusty
group: edge
sudo: true
before_install:
- if [[ "${BUILDER}" = "docker" ]] ; then sudo apt-get update -yqq ; sudo apt-get
  purge -o Dpkg::Options::="--force-confnew" -yqq docker-engine ; sudo apt-get install
  -o Dpkg::Options::="--force-confnew" -yqq docker-engine lvm2 xfsprogs ; echo 'DOCKER_OPTS="$DOCKER_OPTS
  --storage-driver devicemapper"' | sudo tee -a /etc/default/docker ; sudo service
  docker restart ; fi
install:
- git clone --branch="meat-image-metadata-cleanup" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf 0d2c7a6a9209 ; popd
- "./packer-templates/bin/packer-build-install"
script:
- export PACKER_TEMPLATES_BRANCH="meat-image-metadata-cleanup"
- "./packer-templates/bin/packer-build-script ci-connie"
- export PACKER_BUILD_IMAGE_NAME=$(cat ./packer-templates/tmp/ci-connie/latest-image-name
  || echo empty)
- touch ./packer-templates/tmp/image-metadata-$PACKER_BUILD_IMAGE_NAME.tar.bz2
- cp -v ./packer-templates/tmp/image-metadata-$PACKER_BUILD_IMAGE_NAME.tar.bz2 ./image-metadata-$PACKER_BUILD_IMAGE_NAME.tar.bz2
addons:
  artifacts:
    paths:
    - image-metadata-$PACKER_BUILD_IMAGE_NAME.tar.bz2
    target_paths:
    - travis-ci/packer-templates/ci-connie/$BUILDER
env:
  matrix:
  - BUILDER=googlecompute
  - BUILDER=docker
