---
language: minimal
dist: trusty
group: edge
sudo: true
before_install:
- if [[ "${BUILDER}" = "docker" ]] ; then sudo apt-get update -yqq ; sudo apt-get
  purge -o Dpkg::Options::="--force-confnew" -yqq docker-ce ; sudo apt-get install
  -o Dpkg::Options::="--force-confnew" -yqq docker-ce lvm2 xfsprogs ; echo 'DOCKER_OPTS="$DOCKER_OPTS
  --storage-driver devicemapper"' | sudo tee -a /etc/default/docker ; sudo service
  docker restart ; fi
install:
- git clone --branch="cha-meat-mysql-priv-checks" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf eacc90007767 ; popd
- "./packer-templates/bin/packer-build-install"
script:
- export PACKER_TEMPLATES_BRANCH="cha-meat-mysql-priv-checks"
- "./packer-templates/bin/packer-build-script ci-connie"
addons:
  artifacts:
    paths:
    - image-metadata-$(cat .packer-build-image-name).tar.bz2
    target_paths:
    - travis-ci/packer-templates/ci-connie/$BUILDER
env:
  matrix:
  - BUILDER=googlecompute
  - BUILDER=docker
