
language: minimal
dist: xenial

install:
- git clone --branch=lxd-templates "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates

env:
  global:
    - BUILDER="lxd"
    - TEMPLATE="ubuntu-16.04-minimal"
  jobs:
    - stage: "Minimal"
      env:
      - TEMPLATE="ubuntu-16.04-minimal" ARCH="arm64" BUILDER_HOST=$BUILDER_arm64
      - TEMPLATE="ubuntu-18.04-minimal" ARCH="arm64" BUILDER_HOST=$BUILDER_arm64
    - stage: "Ruby"
      env:
      - TEMPLATE="ubuntu-16.04-ruby" ARCH="arm64" BUILDER_HOST=$BUILDER_arm64
      - TEMPLATE="ubuntu-18.04-ruby" ARCH="arm64" BUILDER_HOST=$BUILDER_arm64

before_script:
- |
  echo '
  Host *
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
  '>> ~/.ssh/config
- eval $BUILDER_KEY
- eval $BUILDER_KEY1

script:
- make $TEMPLATE
