---
language: generic
dist: trusty
group: edge
sudo: true
before_install:
- if [[ $BUILDER = docker ]] ; then sudo stop docker ; sudo cat /etc/default/docker
  ; echo 'DOCKER_OPTS="$DOCKER_OPTS --storage-opt dm.basesize=20G"' | sudo tee -a
  /etc/default/docker ; sudo cat /etc/default/docker ; sudo start docker ; sleep 5
  ; sudo docker version ; fi
install:
- git clone --branch="master" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf ffe0e64691105d6da091917f2270881ff837bd8e
  ; popd
- "./packer-templates/bin/packer-build-install"
script:
- "./packer-templates/bin/packer-build-script ci-amethyst"
env:
  matrix:
  - BUILDER=googlecompute
  - BUILDER=docker
