---
language: generic
dist: trusty
group: edge
sudo: true
before_install:
- if [[ "${BUILDER}" = "docker" ]] ; then sudo apt-get update -yqq ; sudo apt-get
  purge -o Dpkg::Options::="--force-confnew" -yqq docker-engine ; sudo apt-get install
  -o Dpkg::Options::="--force-confnew" -yqq docker-engine lvm2 xfsprogs ; echo 'DOCKER_OPTS="$DOCKER_OPTS
  --storage-driver devicemapper"' | sudo tee -a /etc/default/docker ; sudo service
  docker restart ; fi
install:
- git clone --branch="master" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf a3a3143a9210 ; popd
- "./packer-templates/bin/packer-build-install"
script:
- export PACKER_TEMPLATES_BRANCH="master"
- "./packer-templates/bin/packer-build-script tmate-edge"
addons:
  artifacts:
    paths:
    - image-metadata-$(cat .packer-build-image-name).tar.bz2
    target_paths:
    - travis-ci/packer-templates/tmate-edge/$BUILDER
env:
  matrix:
  - BUILDER=amazon-ebs
  - BUILDER=googlecompute
