
language: minimal
dist: xenial

install:
- git clone --branch=lxd-templates "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates

env:
  global:
    - BUILDER="lxd"
    - TEMPLATE="ubuntu-16.04-minimal"
  jobs:
    - ARCH="ppc64le"; BUILDER_HOST=$BUILDER_ppc64le
    - ARCH="arm64"; BUILDER_HOST=$BUILDER_arm64; KEY=$KEY_arm64

before_script:
- echo $KEY_arm64 > .ssh/id_rsa

script:
- export PACKER_BUILD_NAME=$(uuidgen)
- make $TEMPLATE
