---
language: generic
dist: trusty
group: edge
sudo: true
before_install:
- if [[ "${BUILDER}" = "docker" ]] ; then sudo apt-get update -yqq ; sudo apt-get
  purge -o Dpkg::Options::="--force-confnew" -yqq docker-engine ; sudo apt-get install
  -o Dpkg::Options::="--force-confnew" -yqq docker-engine lvm2 xfsprogs ; echo 'DOCKER_OPTS="$DOCKER_OPTS
  --storage-driver devicemapper"' | sudo tee -a /etc/default/docker ; sudo service
  docker restart ; fi
- export TRAVIS_COOKBOOKS_BRANCH=meat-pyenv-python-cleanups
install:
- git clone --branch="cha-dev-trusty-Q2" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf 7938fa8cdd83 ; popd
- "./packer-templates/bin/packer-build-install"
script:
- export PACKER_TEMPLATES_BRANCH="cha-dev-trusty-Q2"
- "./packer-templates/bin/packer-build-script ci-sugilite"
addons:
  artifacts:
    paths:
    - image-metadata-$(cat .packer-build-image-name).tar.bz2
    target_paths:
    - travis-ci/packer-templates/ci-sugilite/$BUILDER
env:
  matrix:
  - BUILDER=googlecompute
