---
language: minimal
dist: focal
group: edge
sudo: true
before_install:
- if [[ "${BUILDER}" = "docker" ]] ; then sudo apt-get update -yqq ; sudo apt-get
  install apt-transport-https gnupg-agent software-properties-common ; curl -fsSL
  https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - ; sudo apt-get
  purge -o Dpkg::Options::="--force-confnew" -yqq docker-ce ; sudo add-apt-repository
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  ; sudo apt-get install -o Dpkg::Options::="--force-confnew" -yqq docker-ce docker-ce-cli
  containerd.io lvm2 xfsprogs ; sudo service docker restart ; fi
- if [[ "${BUILDER}" = "qemu" ]] ; then sudo apt-get update -yqq ; sudo apt-get install qemu-kvm 
  libvirt-daemon-system qemu-utils libvirt-clients bridge-utils cpu-checker unzip cloud-image-utils 
  libvirt-clients -y ; sudo adduser travis libvirt ; sudo adduser travis kvm ; sudo usermod -aG kvm $(whoami) ; 
  sudo usermod -aG libvirt $(whoami) ; virsh list ; cloud-localds user-data.img user-data ; fi

install:
- export PACKER_TEMPLATES_BRANCH="cs-kvm"
- export TRAVIS_COOKBOOKS_BRANCH="master"
- export TRAVIS_COOKBOOKS_EDGE_BRANCH="master"
- if [[ "${BUILDER}" = "qemu" ]] ; then export PACKER_VERSION="1.6.1" ; fi
- git clone --branch="${PACKER_TEMPLATES_BRANCH}" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf @ ; popd
- "./packer-templates/bin/packer-build-install"
script:
- if [[ "${BUILDER}" = "qemu" ]] ; then cp ./user-data.img ./packer-templates/ ; fi
- sudo su -m $USER -c "PACKER_VERSION="1.6.1" ./packer-templates/bin/packer-build-script ci-ubuntu-1804"
addons:
  artifacts:
    paths:
    - image-metadata-$(cat .packer-build-image-name).tar.bz2
    target_paths:
    - travis-ci/packer-templates/ci-ubuntu-1804/$BUILDER
notifications:
  email: false
env:
  matrix:
  - BUILDER=qemu
