---
language: generic
dist: trusty
group: edge
sudo: true
env:
  matrix:
  - BUILDER=googlecompute
  - BUILDER=docker
install:
- echo ohai
script:
- if [[ ci-sardonyx.yml =~ yml ]] ; then packer build -only=${BUILDER} <( ruby -rjson
  -ryaml -rerb -e " puts JSON.pretty_generate( YAML.load(ERB.new(STDIN.read).result)
  ) " < ci-sardonyx.yml ) ; else packer build -only=${BUILDER} ci-sardonyx.yml ; fi
