---
language: minimal
dist: bionic
group: dev
sudo: true
env:
  global:
  - PACKER_TEMPLATES_BRANCH="master"
  - TRAVIS_COOKBOOKS_BRANCH="master"
before_install:
- if [[ "${BUILDER}" = "docker" ]] ; then echo 'DOCKER_OPTS="$DOCKER_OPTS
  --storage-driver devicemapper"' | sudo tee -a /etc/default/docker ;
  sudo systemctl restart docker ; fi
install:
- git clone --branch="master" "https://github.com/travis-ci/packer-templates.git"
- pushd packer-templates && git checkout -qf @ ; popd
- "./packer-templates/bin/packer-build-install"
script:
- "./packer-templates/bin/packer-build-script ci-ubuntu-1804-minimal"
addons:
  artifacts:
    paths:
    - image-metadata-$(cat .packer-build-image-name).tar.bz2
    target_paths:
    - travis-ci/packer-templates/ci-ubuntu-1804-minimal/$BUILDER
notifications:
  email: false
env:
  matrix:
  - BUILDER=googlecompute
  - BUILDER=docker
