language: generic

dist: trusty

sudo: true

env:
  global:
  - PATH="/usr/local/packer:$PATH"
  - PACKER_VERSION='0.10.1'

install:
- curl -sSL -o packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
- sudo unzip packer.zip -d /usr/local/packer
- git clone --depth=1 https://github.com/travis-ci/packer-templates.git
- mkdir -p packer-templates/tmp
- echo $GCE_ACCOUNT_FILE_B64_BZ2 | base64 -d | bunzip2 > packer-templates/tmp/gce.json

script:
- cd packer-templates &&
  make &&
  packer build -only=googlecompute <(bin/yml2json < ci-minimal.yml)
